package tutorials;

import com.github.chen0040.drools.tutorials.Item;
import com.github.chen0040.drools.tutorials.Customer;

rule "Categorize customer - SILVER"
    when
        $o: Order( orderLines.size >= 5, $customer: customer )
        $c: Customer( this == $customer, category == Customer.Category.NA)
    then
        System.out.println("Set customer's category to silver: " + $c);
        modify($c) {
            setCategory(Customer.Category.SILVER)
        };
end

rule "Category customer - GOLD"
    when
        $c: Customer ( category == Customer.Category.NA)
        $o: Order ( customer == $c, orderLines.size() > 10)
    then
        modify($c) {
            setCategory(Customer.Category.GOLD)
        };
end
